### ISSUE TITLE
Some editorial comments

### ISSUE THREAD

**Issue by jimjyang** [SEMICeu/style-guide#56]
1.  [Section Attribute definition and usage](https://semiceu.github.io/style-guide/public-review/gc-conceptual-model-conventions.html#sec:cmc-r10), Examples: the text says that the ePO- ontology uses the "type" attribute converted to a dependency connector, but the figure doesn't show this.
2.  [Section Multiplicity of attributes and connectors](https://semiceu.github.io/style-guide/public-review/gc-conceptual-model-conventions.html#sec:cmc-r11), Examples: 
2a.  `[0..\*]` --> `[0..*]`
2b. The text says "right" and "left", but the figures are aligned vertically. 
4.  [Section Limited (OWL 2) expressivity](https://semiceu.github.io/style-guide/public-review/gc-semantic-conventions.html#sec:sc-r2), second last paragraph before the examples, see the bolded and italic part of the following sentence which should be corrected: "The need for setting property domain and range constraints **_shall be is better_** fulfilled by the data shapes expressed in SHACL language."
5.  [Section URI dereferencing](https://semiceu.github.io/style-guide/public-review/gc-publication-conventions.html#sec:pc-r5), second last paragraph, this sentence is incomplete: "The other representations/formats."
6.  [Section References](https://semiceu.github.io/style-guide/public-review/references.html), the link for [puri-gov-eu] points to joinup in general, not that particular publication.

**Comment by csnyulas** [comment]
**Points 2**, **3** and **5** have been addressed with the above commits.

Regarding **point 1**, it is not that straightforward to show how the relationship `cccev:type` is converted to a dependency connector, because in fact in ePO the  `cccev:type` property is reused only at the level of the `cccev:Citerion` subclass of the `cccev:Requirement` class, not at the level of the `cccev:Requirement` class itself.
![image](https://user-images.githubusercontent.com/2441046/236789214-c0435235-3ecc-4f46-a044-22722e4881d0.png)

@costezki should we add this screen shot, or should we try, perhaps, to provide a different example. For example, we could should how the  `cccev:confidentialityLevelType` propety is converted into a dependency connector in case of the `cccev:Evidence` class. Although this example is not that nice (missing some of the complexity and relevance of the original), at least it is cleaner and clearer.

In CCCEV:
![image](https://user-images.githubusercontent.com/2441046/236790707-5554de52-2b40-472b-a078-00eb12096407.png)

reused in ePO:

![image](https://user-images.githubusercontent.com/2441046/236790043-55f0e1bc-e3e6-4d71-af61-2c4cc07b363d.png)

**Comment by csnyulas** [comment]
Regarding **point 4** :
"[Section URI dereferencing](https://semiceu.github.io/style-guide/public-review/gc-publication-conventions.html#sec:pc-r5), second last paragraph, this sentence is incomplete: "The other representations/formats.""

@bertvannuffelen or @costezki do you know what was the idea that we wanted to convey here?
"The HTML representation should have landing points based on the used fragment identifier. **The other representations/formats.** Further technical details can be found in "Best Practice Recipes for Publishing RDF Vocabularies" [[rdf-pub](https://semiceu.github.io/style-guide/public-review/references.html#ref:rdf-pub)]."

I looked at the edit history, and this sentence was always incomplete. If neither of you has a recollection or idea of what we want to say here, we should drop this sentence.

**Comment by csnyulas** [comment]
We are closing this issue, as all 5 points have been addressed (see related commits).
Thank you for the feedback and very onto the point suggestions, @jimjyang .
